---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: network-conf-1
  namespace: csrx

spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "bridge",
    "master": "eno2",
    "promiscMode": true
}'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: network-conf-2
  namespace: csrx

spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "bridge",
    "master": "eno3",
    "promiscMode": true
}'
